# Generated by Django 4.2.1 on 2023-05-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('global_score', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('hotel_stars', models.IntegerField()),
                ('price', models.FloatField()),
                ('geolocation', models.TextField()),
                ('sustainable_trip', models.BooleanField()),
                ('accept_pay_cards', models.BooleanField()),
                ('accept_cash', models.BooleanField()),
                ('security_cameras', models.BooleanField()),
                ('includes_breakfast', models.BooleanField()),
                ('english', models.BooleanField()),
                ('distance_to_beach', models.FloatField()),
                ('distance_to_beach_meters', models.FloatField()),
                ('indicator_distance_to_beach', models.BooleanField()),
                ('distance_to_historical_center', models.FloatField()),
                ('distance_to_Centro_historico_metros', models.FloatField()),
                ('indicador_distance_to_Centro_historico', models.BooleanField()),
                ('distance_to_Muelle_y_punto_Policia_de_turismo', models.FloatField()),
                ('distance_to_Muelle_y_punto_Policia_de_turismo_Metros', models.FloatField()),
                ('indicator_distance_to_Muelle_y_punto_Policia_de_turismo', models.BooleanField()),
                ('personal_score', models.FloatField()),
                ('instalations_score', models.FloatField()),
                ('cleanliness_score', models.FloatField()),
                ('confort_score', models.FloatField()),
                ('price_quality_score', models.FloatField()),
                ('location_score', models.FloatField()),
                ('free_wifi_score', models.FloatField()),
            ],
        ),
    ]
